version: "3.3"
services:
  bitcoind:
    image: kylemanna/bitcoind
    entrypoint: ["btc_oneshot"]
    command: ["-txindex", "-rpcbind=:18444", "-rpcallowip=0.0.0.0/0", "-regtest"]
    ports:
      - 18443:18443
      - 18444:18444
    environment:
      RPCUSERNAME: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
    restart: unless-stopped
  keydb:
    image: eqalpha/keydb
    command:
      [
        "keydb-server",
        "/etc/keydb/keydb.conf",
        "--storage-provider",
        "flash",
        "/data/flash",
        "--appendonly",
        "yes",
        "--maxmemory-policy",
        "allkeys-lru",
        "--bind",
        "0.0.0.0"
      ]
    restart: unless-stopped
  metashrew:
    build:
      dockerfile: docker/Dockerfile.indexer
      context: ./
    image: metashrew/metashrew
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18445
      AUTH: bitcoinrpc:bitcoinrpc
      REDIS_URL: redis://keydb:6379
    restart: unless-stopped
  metashrew-view:
    build:
      dockerfile: docker/Dockerfile.view
      context: ./
    image: metashrew/metashrew-view
    environment:
      REDIS_URL: redis://keydb:6379
    ports:
      - 3000:8080
    restart: unless-stopped
