version: "3.3"
services:
  bitcoind:
    image: ruimarinho/bitcoin-core
    command:
      ["-txindex", "-regtest=1", "-printtoconsole", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=bitcoinrpc", "-rpcpassword=bitcoinrpc"]
    ports:
      - 18555:18443
      - 18444:18444
    restart: unless-stopped
  keydb:
    ports:
      - 7777:6379
    image: eqalpha/keydb:unstable
    command:
      [
        "keydb-server",
        "/etc/keydb/keydb.conf",
        "--storage-provider",
        "flash",
        "/data/flash",
        "--appendonly",
        "yes",
        "--maxmemory-policy",
        "allkeys-lru",
        "--bind",
        "0.0.0.0",
      ]
    restart: unless-stopped
  metashrew:
    build:
      dockerfile: docker/Dockerfile.indexer
      context: ./
    image: rockshrew:alkanes
    environment:
      DAEMON_RPC_ADDR: http://bitcoind:18443
      AUTH: bitcoinrpc:bitcoinrpc
      DB_PATH: /data
      LOG_FILTERS: none,rockshrew=debug
    restart: unless-stopped
  jsonrpc:
    build:
      dockerfile: docker/Dockerfile.jsonrpc
      context: ./
    image: jsonrpc:alkanes
    environment:
      HOST: 0.0.0.0
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      DAEMON_RPC_ADDR: bitcoind:18443
      ORD_HOST: ord
      ORD_PORT: 8090
      PORT: 18888
    ports:
      - 18888:18888
    restart: unless-stopped
  ord:
    build:
      dockerfile: docker/Dockerfile.ord
      context: ./
    image: ord:alkanes
    environment:
      CHAIN: regtest
      RPCUSER: bitcoinrpc
      RPCPASSWORD: bitcoinrpc
      PORT: 8090
      DAEMON_RPC_ADDR: bitcoind:18443
    ports:
      - 8090:8090
    restart: unless-stopped
  metashrew-view:
    build:
      dockerfile: docker/Dockerfile.view
      context: ./
    image: metashrew-view:alkanes
    environment:
      REDIS_URL: redis://keydb:6379
      HOST: 0.0.0.0
      LOG_FILTERS: none,metashrew_keydb_view=debug
    ports:
      - 8080:8080
    restart: unless-stopped
