version: "3.3"
services:
  dogecoin:
    image: metashrew/dogecoin
    entrypoint: ["doge_oneshot"]
    command:
      ["-txindex", "-regtest=1", "-printtoconsole", "-rpcallowip=0.0.0.0/0", "-rpcbind=0.0.0.0", "-rpcuser=dogecoinrpc", "-rpcpassword=dogecoinrpc", "-rpcport=18443"]
    ports:
      - 18555:18443
      - 0.0.0.0:22556:18444
    restart: unless-stopped
    environment:
      - RPCUSER=dogecoinrpc
      - RPCPASSWORD=dogecoinrpc
  keydb:
    ports:
      - 7777:6379
    image: eqalpha/keydb:unstable
    command:
      [
        "keydb-server",
        "/etc/keydb/keydb.conf",
        "--storage-provider",
        "flash",
        "/data/flash",
        "--appendonly",
        "yes",
        "--maxmemory-policy",
        "allkeys-lru",
        "--bind",
        "0.0.0.0",
      ]
    restart: unless-stopped
  metashrew:
    build:
      dockerfile: docker/Dockerfile.indexer-dogekanes
      context: ./
    image: metashrew:dogekanes
    environment:
      DAEMON_RPC_ADDR: http://dogecoin:18443
      AUTH: dogecoinrpc:dogecoinrpc
      REDIS_URL: redis://keydb:6379
      LOG_FILTERS: none,metashrew_keydb=debug
    restart: unless-stopped
  jsonrpc:
    build:
      dockerfile: docker/Dockerfile.jsonrpc
      context: ./
    image: jsonrpc:dogekanes
    environment:
      HOST: 0.0.0.0
      RPCUSER: dogecoinrpc
      RPCPASSWORD: dogecoinrpc
      DAEMON_RPC_ADDR: dogecoin:18443
      ORD_HOST: ord
      ORD_PORT: 8090
      PORT: 18888
    ports:
      - 18888:18888
    restart: unless-stopped
  metashrew-view:
    build:
      dockerfile: docker/Dockerfile.view-dogekanes
      context: ./
    image: metashrew-view:dogekanes
    environment:
      REDIS_URL: redis://keydb:6379
      HOST: 0.0.0.0
      LOG_FILTERS: none,metashrew_keydb_view=debug
    ports:
      - 8080:8080
    restart: unless-stopped
